### ISSUE TITLE
Error - Refresh token ?

### ISSUE THREAD

**Issue by eijowk** [flopp999/NIBEmyUplink-Domoticz#3]
Errors in Domoticz:

2024-04-08 14:46:21.696 Error: NIBE: Call to function 'onConnect' failed, exception details:
2024-04-08 14:46:21.697 Error: NIBE: Traceback (most recent call last):
2024-04-08 14:46:21.697 Error: NIBE: File "/home/NNN/domoticz/plugins/NIBEmyUplink/plugin.py", line 437, in onConnect
2024-04-08 14:46:21.697 Error: NIBE: _plugin.onConnect(Connection, Status, Description)
2024-04-08 14:46:21.697 Error: NIBE: File "/home/NNN/domoticz/plugins/NIBEmyUplink/plugin.py", line 133, in onConnect
2024-04-08 14:46:21.697 Error: NIBE: data += "&refresh_token="+self.reftoken
2024-04-08 14:46:21.697 Error: NIBE: AttributeError: 'BasePlugin' object has no attribute 'reftoken'

Depending on missing Refresh token?
What is the Refresh token?

**Comment by eijowk** [comment]
Answer my self on this one..
In the Domoticz log - sometimes the Refresh token is presented when the plugin is started. I can see it if I delete the Nibe plugin and ads a new one. Turn off/turn on the plugin doesn't present the refresh token.

**Comment by flopp999** [comment]
I have done some small work, it was an error that I showed some extra text.
Don't care about the refresh token, you need new Auth code everytime you restart Hardware or Domoticz
